version: '3.7'
services:
    mysql:
        image: mysql:8
        restart: on-failure
        env_file: .env
        command: '--default-authentication-plugin=mysql_native_password'
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.7
        ports:
            - ${PHPMYADMIN_PORT:-8887:80}
        depends_on:
            - mysql
        links:
            - mysql:db
    nginx:
        image: nginx:alpine
        restart: on-failure
        env_file: .env
        networks:
            - default
            - reverse-proxy
        volumes:
            - './apps/bracelet/public/:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - ${WEB_PORT:-80:80}
        depends_on:
            - php
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - './apps/bracelet/:/usr/src/app'
        restart: on-failure
networks:
    reverse-proxy:
        external:
            name: reverse-proxy
