# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    routing_loader:
        include_format: false
    param_fetcher_listener: force
    versioning: true
    format_listener:
        enabled: true
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: 'json' }
    view:
        view_response_listener: true
        formats:
            json: true
            xml: false
    exception:
        enabled: true
        messages:
            Symfony\Component\HttpKernel\Exception\HttpException: true
