security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory: { memory: ~ }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
#            provider:  fos_userbundle
            pattern:   ^/api
            stateless: true
            anonymous: true
        main:
            context: user
            form_login:
                provider: fos_userbundle
                login_path: /login
                check_path: /login_check
                default_target_path: /login/redirect
                always_use_default_target_path: true
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 2419200 # 4 semaines
                path:     /
            logout:       true
            anonymous:    true
            logout_on_user_change: true

    role_hierarchy:
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_ADMIN: ROLE_USER
        ROLE_USER: IS_AUTHENTICATED_FULLY

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [ROLE_USER] }

    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: bcrypt
            cost: 12
